### ISSUE TITLE
Persistent shortcut challenges

### ISSUE THREAD

**Issue by RDIL** [thepeacockproject/Peacock#16]
- [x] Global challenges appear in missions they should not (did @AnthonyFuller fix this?)
- [ ] Make them actually completable
- [ ] Add dugong ones

**Comment by AnthonyFuller** [comment]
>  Global challenges appear in missions they should not (did @AnthonyFuller fix this?)

Define this behaviour.

**Comment by RDIL** [comment]
The ladders/door challenges for the Persistent Shortcuts are sent to the game even when not on the intended map, which is not the same behavior as the official servers.

**Comment by AnthonyFuller** [comment]
Yes, this was fixed in the Evergreen branch by:
1. Following what inclusion data says (like we do with challenges, these systems should be merged no?)
2. Adding a location into their inclusion data, I assume what IOI do is check if they unlocked the actual challenge linked to it and send it that way, we can change that if wanted, (possibly adding our own inclusion data?)

**Comment by RDIL** [comment]
Yeah.  Now all that remains is cherry-picking that behavior onto the main branch.
