### ISSUE TITLE
The context of some freelancer challenges are not saved

### ISSUE THREAD

**Issue by moonysolari** [thepeacockproject/Peacock#201]
This is My Rifle, Collector, One Shot One Kill, Up Close and Personal, etc. are not having their contexts saved to the user's profile. So the bar pops up on the upper right corner when you go into the safehouse even if the number of rifles, for example, hasn't changed.

The reason they are not saved is that they have `"Scope": "session"`, and the context is only saved when the `Scope` is `"hit"` or `"profile"`. However, I think that the context should also be saved for these challenges.

**Comment by AnthonyFuller** [comment]
I do believe this is an "issue" on official too, this is most likely due to the fact that you need them "on the safehouse wall". So if you have 8, then lose one on a mission, your progress to that challenge is now 7. Yes, it's definitely annoying, but unfortunately it just has to be that way due to the nature of the challenge.

You could definitely design around it, maybe by `$set`ting the progress on the profile every time the event is recieved, but I guess we'll see.
