### ISSUE TITLE
"Big Brother" objective not showing on the planning page in The Montague Audacity Level 3

### ISSUE THREAD

**Issue by moonysolari** [thepeacockproject/Peacock#287]

**Comment by RDIL** [comment]
cc @grappigegovert - mapObjectives?

**Comment by grappigegovert** [comment]
> cc @grappigegovert - mapObjectives?

I was meaning to look into this, thanks for the reminder

**Comment by grappigegovert** [comment]
Looks like this is an issue with the contract json, it's not clean.
Gamechangers are baked into the objectives instead of using the gamechanger id in the `Gamechangers` property, and `GroupObjectiveDisplayOrder` is missing.

Replacing the contract json with a clean copy from IOI's servers resolves this issue, but it looks like this might be a problem for some other escalations: a quick check reveals a similar issue with MACMILLAN3.json, that one doesn't even have the right contract id, and there are probably more.
@RDIL Thoughts?

**Comment by RDIL** [comment]
Odd. @Kakiking any ideas what happened?

**Comment by AnthonyFuller** [comment]
They most likely used GetForPlay2 and did not remove the applied objectives.

**Comment by grappigegovert** [comment]
The reason I (wrongly) noted the ID issue was because I was looking at the old repo while trying to locate the origin of the bug.
I think all ID issues were resolved in the escalation rewrite.

Should we just update all contracts with fresh copies from IOI's servers?
I think tracking down issues with individual contracts will take more time

**Comment by moonysolari** [comment]
> Should we just update all contracts with fresh copies from IOI's servers?

I think it's the best solution. Also I don't remember fixing the IDs...

**Comment by Kakiking** [comment]
> Odd. @Kakiking any ideas what happened?
Maybe that was because the JSON was from Hitman 2 servers?
