### ISSUE TITLE
Remove hard-coded credentials

### ISSUE THREAD

**Issue by RDIL** [thepeacockproject/Peacock#310]
When the `developmentAllowRuntimeRestart` flag is false, we should generate a random secret every time Peacock is started.

Tracking issue for:
- [ ] https://github.com/thepeacockproject/Peacock/security/code-scanning/7
- [ ] https://github.com/thepeacockproject/Peacock/security/code-scanning/8

**Comment by AnthonyFuller** [comment]
I think for v7, we should remove that option, and just check the environment.

**Comment by AnthonyFuller** [comment]
I have just committed to generate random secrets as required, but I'd like some comments on removing the `developmentAllowRuntimeRestart` option.

**Comment by AnthonyFuller** [comment]
> I have just committed to generate random secrets as required, but I'd like some comments on removing the `developmentAllowRuntimeRestart` option.

Could I get some?

**Comment by RDIL** [comment]
I'm in favor of that, since it's functionally the same mechanism. cc @LennardF1989

**Comment by LennardF1989** [comment]
The idea of the development restart is that you don't have to go offline/online in-game and just continue as you were doing. Changing the key from one run to the other would invalidate the JWT token, no? In some cause it will do a re-auth flow, but sometimes you are quick enough to restart.

I'm all up for doing something randomly generated, but would be great if it's deterministic (eg. based on the current system date, you always get the same key).

In the end, we are try to get rid of a hardcoded value simply because some Github bot is screaming about it - while in essence, since this is a local server thing, the value doesn't matter.

Alternative: generate a unique key per profile and keep using that, or just use the profile GUID itself. Just thinking out loud.

**Comment by RDIL** [comment]
More like i’m trying to get rid of the value because I know there are some people who use peacock as a public server, which poses a security risk. But as Tony said, we could have it be deterministic in development mode, and random in production mode. That’s the best of both worlds in my eyes.

**Comment by LennardF1989** [comment]
Yes, I agree. Best of both worlds would be deterministic in dev mode, random otherwise. This should also leave the developmentAllowRuntimeRestart functionality intact :)

**Comment by AnthonyFuller** [comment]
Well no, we have the `PEACOCK_DEV` environment variable for a reason.

**Comment by LennardF1989** [comment]
> Well no, we have the `PEACOCK_DEV` environment variable for a reason.

Not sure I understand what you mean by this. Are you implying there is no need for such a switch, because enabling dev mode on itself should just perform this functionality by default and thus no need to toggle it on or off?

**Comment by AnthonyFuller** [comment]
> Are you implying there is no need for such a switch, because enabling dev mode on itself should just perform this functionality by default and thus no need to toggle it on or off?

Yes, there's no need for pointless options when there was already an existing solution for that.

**Comment by LennardF1989** [comment]
I think the whole reason this switch became a thing is because @RDIL didn't want to enable the functionality enabled by default. 

No objections in getting rid of this line:
https://github.com/thepeacockproject/Peacock/blob/9f3d243377994e4a7abf8468073334381d583360/components/index.ts#L378

And replacing it with the PEACOCK_DEV check.

**Comment by AnthonyFuller** [comment]
I don't see a reason for this not to be the case in dev, if you're running it in dev you already know that it would be in-secure.

**Comment by RDIL** [comment]
The original reason for not having it on by default is because we don't want it making up sessions in cases like this unless we explicitly know what we're doing because that would mess with scoring a ton.

**Comment by RDIL** [comment]
But yeah I'm fine with this in dev
