### ISSUE TITLE
Contracts on Hawke's Bay start without NPC's

### ISSUE THREAD

**Issue by jkolbly** [thepeacockproject/Peacock#354]
**Describe the bug**
Contracts can be created on the map Hawke's Bay as usual, but when they are played, the game will act as if you are playing the story. That is, there are no NPC's on the map until the computer in the office is searched and the story cutscene plays.

This makes contracts in Hawke's Bay essentially unfeasible.

**To reproduce**
Create a contract on the map Hawke's Bay, publish it, then play it. There will be no NPC's on the map until you search the computer in the office and the cutscene plays.

**Additional context**
I have verified that this is a Peacock-specific issue (contracts work as expected without Peacock and have all NPC's as soon as you spawn in).

**Comment by RDIL** [comment]
@jkolbly this should now be fixed in the latest v7 branch build, you can download it [here](https://cirrus-ci.com/task/5908159416500224) under the artifacts > Peacock_Release section! Let me know if it works (I'm 99.9% sure it will, but haven't tested it yet). Also, the fix will only apply to contracts created with the new release, not existing ones.

**Comment by jkolbly** [comment]
It works! Thank you for the quick response!
