### ISSUE TITLE
Escalation challenges are not hooked to the corresponding escalations

### ISSUE THREAD

**Issue by moonysolari** [thepeacockproject/Peacock#78]
**Describe the bug**
- Finishing an escalation mission does not complete the corresponding escalation challenge.
- No escalation challenge can be found under the "FEATS" category on the Challenges tab in the planning page of any escalation mission, in the F1 page in-game, or on the mission-end screen.
- When viewed on the Challenges tab in the location page, no escalation challenge shows the shortcut to the corresponding escalation mission below its tile (see screenshots).

**Additional context**
Official:
![image](https://user-images.githubusercontent.com/118079569/211744683-a608376c-2a20-44a5-87e0-4c3fbc297274.png)
Peacock:
![image](https://user-images.githubusercontent.com/118079569/211744789-1dba861a-6024-4c2a-ada2-51bd4ea71b7b.png)

**Comment by AnthonyFuller** [comment]
I must've missed this issue. When I was implementing that feature (with the "Destination" challenges overhaul), I noticed this was an issue and made a remark about it somewhere.

The issue is that Peacock does not use escalation groups "properly", it has a faux escalation group defined in a file. Since there was no facility to easily generate these like there is for missions, I left it out for a future thing to be added.
